### PR TITLE
Fixes NewRelic error when SessionStorage property of window is not accessible.

### LINKED ISSUE #268: Accessing sessionStorage may throw errors if a browser is configured to not support it
# Bug Report

Accessing sessionStorage may throw errors if a browser is configured to not support it. See this article for more information on how this might happen and how to detect it: https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API We should handle this scenario more gracefully where we access session storage in dev site

### PR DESCRIPTION
**Pull request by ShettyAkarsh**
### Summary
When cookies are blocked using the browser settings for the sites consuming dev-site. there is a error getting logged in new relic 'Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document'. 

This is mainly because of the sessionStorage property of Window object will not be accessible due to the above settings. this fix will ensure whether the sessionStorage property is accessible before retrieving any values from it and writing into it.

Closes #268 

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: src/redirect.js [hunk 1]
```diff
@@ -6,6 +6,16 @@
...
+// Function to check if sessionStorage property is readable.
+function getSessionStorage() {
+  try {
+    return window.sessionStorage;
+  } catch (e) {
+    return undefined;
+  }
+}
+
+if (getSessionStorage() !== undefined) { window.sessionStorage.redirect = window.location.href; }
```
Comment (emilyrohrbough) [inline src/redirect.js:19]: could you do this?
```suggestion
try {
    window.sessionStorage.redirect = window.location.href;
  } catch (e) {
    // window.sessionStorage is not supported
  }
```

File: src/site/_Site.jsx [hunk 2]
```diff
@@ -36,6 +36,14 @@ const propTypes = {
...
 };
 
+const getSessionStorage = () => {
+  try {
+    return window.sessionStorage;
+  } catch (e) {
+    return undefined;
+  }
+};
+
```
Comment (emilyrohrbough) [inline src/site/_Site.jsx:46]: Is this something we can pull out to be re-usable?

File: src/redirect.js [hunk 3]
```diff
@@ -6,6 +6,16 @@
 // returning a 404 page that stores the requested path and redirects to index.html
 // to allow the SPA router to handle the route.
 // Store the not found window location in session storage
-window.sessionStorage.redirect = window.location.href;
+
+// Function to check if sessionStorage property is readable.
+function getSessionStorage() {
+  try {
+    return window.sessionStorage;
+  } catch (e) {
```
Comment (yuderekyu) [inline src/redirect.js:14]: should we do something with this error? i could see us maybe? logging an error if we aren't in a prod environment.
not a big deal though ¯\_(ツ)_/¯

File: src/site/_Site.jsx (hunk 2 above)
Comment (ShettyAkarsh) [reply src/site/_Site.jsx]: Moved it to reusable [here](https://github.com/cerner/terra-dev-site/blob/dabf4ceeb0af7bb59540f67283903594e29ac755/src/session.js)

File: src/redirect.js (hunk 3 above)
Comment (ShettyAkarsh) [reply src/redirect.js]: Updated [here](https://github.com/cerner/terra-dev-site/blob/abad0a32f0ece49a9dfdc5bb5d125317c34a6d1c/src/session.js#L6-L9)

File: src/redirect.js [hunk 4]
```diff
@@ -6,6 +6,11 @@
 // returning a 404 page that stores the requested path and redirects to index.html
 // to allow the SPA router to handle the route.
 // Store the not found window location in session storage
-window.sessionStorage.redirect = window.location.href;
+
+try {
+  window.sessionStorage.redirect = window.location.href;
+} catch (e) {
+  // window.sessionStorage is not readable.
+}
```
Comment (emilyrohrbough) [inline src/redirect.js:14]: Can this also use the re-usable func?

**Comment by mjhenkes** [comment]
How does this look to a user when it fails? I would like a clear message face up so users don't have to troubleshoot a white screen.

**Comment by ShettyAkarsh** [comment]
> How does this look to a user when it fails? I would like a clear message face up so users don't have to troubleshoot a white screen.

@mjhenkes , After this fix the Page reloads. the only difference will be is if the cookies are blocked then when the page loads always the first navigation item will be selected.
whereas when the cookies are not blocked then previously selected navigation item used to get selected. as we pick that value from sessionStorage.

File: src/redirect.js [hunk 5]
```diff
@@ -6,6 +6,10 @@
 // returning a 404 page that stores the requested path and redirects to index.html
 // to allow the SPA router to handle the route.
 // Store the not found window location in session storage
-window.sessionStorage.redirect = window.location.href;
+
+import getSessionStorage from './session';
+
+if (getSessionStorage() !== undefined) { window.sessionStorage.redirect = window.location.href; }
```
Comment (emilyrohrbough) [inline src/redirect.js:12]:
```suggestion
if (getSessionStorage() !== undefined) {
  window.sessionStorage.redirect = window.location.href;
}
```

File: src/site/_Site.jsx [hunk 6]
```diff
@@ -50,7 +51,7 @@ class Site extends React.Component {
    */
   redirectToReservedRoute({ match }) {
     const { siteConfig } = this.props;
-    window.sessionStorage.redirect = window.location.href;
+    if (getSessionStorage() !== undefined) { window.sessionStorage.redirect = window.location.href; }
```
Comment (emilyrohrbough) [inline src/site/_Site.jsx:54]:
```suggestion
    if (getSessionStorage() !== undefined) {
      window.sessionStorage.redirect = window.location.href;
    }
```
