### PR TITLE
Remove the ability to explicitly configure bidirectionality from app config.

### LINKED ISSUE #209: Disabling bi-directionality in setttings no longer
# Bug Report

## Description
[Bidirectionally configuration is defined in the appSite configuration](https://github.com/cerner/terra-dev-site/blob/master/config/site/site.config.js#L87), however this value is [not being checked when generating the settings config](https://github.com/cerner/terra-dev-site/blob/master/scripts/generate-app-config/generateSettingsConfig.js#L16).

### PR DESCRIPTION
**Pull request by nramamurth**
### Summary
Closes #209.

### CODE REVIEW

File: scripts/generate-app-config/generateSettingsConfig.js [hunk 1]
```diff
@@ -12,8 +12,8 @@ const generateUtilitiesConfig = (appConfig) => {
     themes: appConfig.themes || {},
     defaultLocale: appConfig.defaultLocale,
     locales: appConfig.locales || {},
-    defaultDirection: appConfig.defaultDir,
-    directions: ['ltr', 'rtl'],
+    defaultDirection: appConfig.defaultDirection,
```
Comment (nramamurth) [inline scripts/generate-app-config/generateSettingsConfig.js]: 👀

File: scripts/generate-app-config/generateSettingsConfig.js [hunk 2]
```diff
@@ -12,8 +12,8 @@ const generateUtilitiesConfig = (appConfig) => {
...
+    directions: appConfig.bidirectional ? ['ltr', 'rtl'] : [],
```
Comment (nramamurth) [inline scripts/generate-app-config/generateSettingsConfig.js]: @emilyrohrbough I functionally tested it but should there be a _wdio_ test? I might need a separate site config just for that, then?

Comment (emilyrohrbough) [reply scripts/generate-app-config/generateSettingsConfig.js]: @nramamurth you should be able to you write a jest test to verify the generated config

File: scripts/generate-app-config/generateAppConfig.js [hunk 3]
```diff
@@ -37,7 +37,7 @@ const addConfig = (config, fileName, buildPath, fs, imports) => {
  * } param0
  */
 const generateAppConfig = ({
-  siteConfig, mode, prefix, apps = [], verbose = false, basename, resolveExtensions,
+  siteConfig, mode, prefix, apps = [], verbose = false, basename, resolveExtensions = [],
```
Comment (emilyrohrbough) [inline scripts/generate-app-config/generateAppConfig.js]: why was a default value added?

Comment (nramamurth) [reply scripts/generate-app-config/generateAppConfig.js]: To prevent the line below from blowing up. I noticed that it blew up when I ran the current `generateAppConfig` script.

https://github.com/cerner/terra-dev-site/blob/91f94d78827b226169aaf3e521066d04b8a33d3f/scripts/generate-app-config/generatePagesConfig.js#L143-L144

File: scripts/generate-app-config/generateSettingsConfig.js (hunk 2 above)
Comment (nramamurth) [reply scripts/generate-app-config/generateSettingsConfig.js]: Ah, my bad. Here it is -  https://github.com/cerner/terra-dev-site/pull/210/commits/9a33b01a68dc5fe84a94ecbb237dd34430713c49

File: scripts/generate-app-config/generateSettingsConfig.js [hunk 4]
```diff
@@ -11,9 +11,9 @@ const generateUtilitiesConfig = (appConfig) => {
     defaultTheme: appConfig.defaultTheme,
     themes: appConfig.themes || {},
     defaultLocale: appConfig.defaultLocale,
-    locales: appConfig.locales || {},
-    defaultDirection: appConfig.defaultDir,
-    directions: ['ltr', 'rtl'],
+    locales: appConfig.locales || [],
```
Comment (nramamurth) [inline scripts/generate-app-config/generateSettingsConfig.js]: I assume this should have been an empty array by default?

File: scripts/generate-app-config/generateAppConfig.js (hunk 3 above)
Comment (mjhenkes) [reply scripts/generate-app-config/generateAppConfig.js]: honestly running that script outside of the webpack plugin probably isn't going to work right anymore.

File: scripts/generate-app-config/generateSettingsConfig.js [hunk 5]
```diff
@@ -11,9 +11,9 @@ const generateUtilitiesConfig = (appConfig) => {
...
+    defaultDirection: appConfig.defaultDirection,
+    directions: appConfig.bidirectional ? ['ltr', 'rtl'] : [],
```
Comment (mjhenkes) [inline scripts/generate-app-config/generateSettingsConfig.js]: Lets just default this to ['ltr', 'rtl'] and remove the bidirectional config from appConfig. I don't think there is a good argument for allowing people to turn this off.

Comment (emilyrohrbough) [reply scripts/generate-app-config/generateSettingsConfig.js]: this actually fixes the next issue I was going to point out 😋 If you turn off config options the settings modal still launches with nothing in it

File: scripts/generate-app-config/generateAppConfig.js (hunk 3 above)
Comment (nramamurth) [reply scripts/generate-app-config/generateAppConfig.js]: Sure, but irregardless of that, I think it's a good idea to default it to an empty array.

File: scripts/generate-app-config/generateSettingsConfig.js (hunk 5 above)
Comment (nramamurth) [reply scripts/generate-app-config/generateSettingsConfig.js]: @mjhenkes That's a good point. I have addressed it here: https://github.com/cerner/terra-dev-site/pull/210/commits/1ddcb551a692c13d2a807a172422a79da3579c08

File: scripts/generate-app-config/generateSettingsConfig.js (hunk 1 above)
Comment (emilyrohrbough) [reply scripts/generate-app-config/generateSettingsConfig.js]: nice catch 👍

File: tests/scripts/generate-app-config/generateSettingsConfig.test.js [hunk 6]
```diff
@@ -0,0 +1,36 @@
+const generateSettingsConfig = require('../../../scripts/generate-app-config/generateSettingsConfig');
+
+describe('settings config', () => {
+  it('returns undefined when app config is not supplied', () => {
+    const config = generateSettingsConfig();
+    expect(config).toEqual(undefined);
+  });
+
+  it('generates settings config with BiDi support', () => {
```
Comment (emilyrohrbough) [inline tests/scripts/generate-app-config/generateSettingsConfig.test.js]:
```suggestion
  it('generates settings with BiDi support by default', () => {
```
