### PR TITLE
Secondary Navigation Menu should not scroll down when selecting item via space bar click

### LINKED ISSUE #259: Secondary Navigation Menu scrolls down when selecting item by clicking spacebar
# Bug Report

## Description

While selecting an item in Secondary Navigation Menu through the spacebar, the navigation scrolls down till it ends.

## Steps to Reproduce

1. Go to https://engineering.cerner.com/terra-dev-site/secondary-nav-test/terra-dev-site/secondary-scroll-test/filler/filler
2. Expand Secondary Scroll Test and all of its child items
3. Select filler and tab to filler 01
4. press the spacebar to select it.

## Additional Context / Screenshots

Screen-Recording-2020-04-27-at-4 12 49-PM

## Expected Behavior

Secondary Navigation should not scroll down when clicking the spacebar

## Environment

* Component Name and Version: NA
* Browser Name and Version: chrome
* Node/npm Version: NA
* Webpack Version: NA
* Operating System and version (desktop or mobile): Mac

### PR DESCRIPTION
**Pull request by pranav300**
### Summary

Added `preventdefault` in `keyDown` event for `space bar and return/enter` key for `Secondary Navigation Menu`.

Closes #259 

### Deployment Link

https://terra-dev-site-deployed-pr-#.herokuapp.com/

### Additional Details

Before: 
ezgif com-video-to-gif

After:
ezgif com-video-to-gif

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: src/navigation/_CollapsingNavigationMenu.jsx [hunk 1]
```diff
@@ -136,6 +136,7 @@ class CollapsingNavigationMenu extends React.Component {
 
   handleKeyDown(event, item) {
     if (event.nativeEvent.keyCode === KeyCode.KEY_SPACE || event.nativeEvent.keyCode === KeyCode.KEY_RETURN) {
+      event.preventDefault();
```
Comment (emilyrohrbough) [inline src/navigation/_CollapsingNavigationMenu.jsx:139]: Is it possible to capture the broken behavior and the fixed behavior in wdio?
