### PR TITLE
[v7] Implement terra-application v2 and Eliminate intermediate build step and config

### LINKED ISSUE #113: Site Build "litters" Repo
# Bug Report

## Description
When using terra-dev-site's webpack configuration, the terra-dev-site generate app-config script is automatically ran. When run, it creates the `dev-site-config/build` directory and generates the site configuration. These configuration files can "litter" the project, where as the packed webpack assets use a virtual file system, so these files do not 'litter' the project. I am wondering if there is a way for these files to be created virtually or be automatically clean after running in webpack.

## Additional Context / Screenshots
screen shot 2018-10-03 at 9 19 40 am

## Possible Solution
Not sure if this is feasible since webpack is a static analysis tool and which is likely why these files are not using a virtual file system as is.

### PR DESCRIPTION
**Pull request by mjhenkes**
### Summary

Whew, ok, this is a big one. I estimate ~70% of terra dev site has been re-written here. The only things that haven't been touched are the loader components and the browser router 404 page.

High level overview of changes:
* terra-dev-site fully converted to a webpack plugin.
* dev-site-config folder removed, intermediate build files no longer written to disk.
* terra-dev-site now configured directly with the webpack config.
* config changed to better align with terra-application (see the config map in the upgrade guide)
* terra-application updated to v2
* secondary navigation removed in favor of terra-application secondary navigation layout
* all content now wrapped in a page
* dependency on terra-toolkit removed.
* no longer offering webpack config to extend, use the webpack plugin.

This PR is still using a git reference to terra-application as it is not yet released that means:
* lowlight theme is not complete for anything using terra application and screenshots will still need to be updated
* terra-application styles are not complete and will change and possibly require changes in the future.

using the git ref should not block this PR from being merged since it is going into the `terra-dev-site-v7` branch and not main. Before v7 can become main, we will need to have released terra-application v2. And besides, this is already a big PR lets get what is here reviewed.

Outstanding UX questions:

* The dev toolbar has mostly been removed with the exception of a 'show raw' icon, What icon should I use?
* Is there a better approach to fast theme and locale switching? Opening the settings menu seems cumbersome.

Closes #113

### Deployment Link

https://terra-dev-site-deployed-pr-#.herokuapp.com/

### Testing

WDIO and jest tests have been update, but as mentioned above the wdio screenshots are not final until terra-application v2 is released.

### Additional Details

Thank you for contributing to Terra.
@cerner/terra

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
-const DirectorySwitcherPlugin = require('./config/webpack/plugin/resolve/DirectorySwitcherPlugin');
-const LocalPackageAliasPlugin = require('./config/webpack/plugin/resolve/LocalPackageAliasPlugin');
-const TerraDevSiteEntrypoints = require('./config/webpack/plugin/TerraDevSiteEntrypoints');
-const TerraDevSite = require('./config/webpack/plugin/TerraDevSite');
+const DirectorySwitcherPlugin = require('./lib/webpack/plugin/resolve/DirectorySwitcherPlugin');
```
Comment (mjhenkes) [inline index.js:1]: all files have been consolidated in source and for webpack files, ignored and copied to lib.

File: package.json [hunk 2]
```diff
@@ -73,7 +70,7 @@
     "clean": "rm package-lock.json; rm -rf node_modules",
     "clean:install": "npm run clean && npm install",
     "clean:obsolete-snapshots": "npm test -- -u",
-    "compile": "babel src --out-dir lib --copy-files",
+    "compile": "babel src --out-dir lib --copy-files  --ignore src/webpack",
```
Comment (mjhenkes) [inline package.json:73]: this ignores the webpack files when compiling and copies them to lib untouched.

File: package.json [hunk 3]
```diff
@@ -103,55 +100,42 @@
...
-    "terra-aggregate-translations": "^1.0.0",
-    "terra-application": "^1.19.0",
     "terra-button": "^3.12.0",
-    "terra-button-group": "^3.5.0",
-    "terra-content-container": "^3.0.0",
     "terra-form-select": "^6.0.0",
     "terra-hyperlink": "^2.9.0",
     "terra-icon": "^3.0.0",
-    "terra-image": "^3.0.0",
     "terra-infinite-list": "^3.5.0",
```
Comment (mjhenkes) [inline package.json:128]: TODO on another PR, remove references to infinite list

File: index.js [hunk 4]
```diff
@@ -1,7 +1,7 @@
...
+const LocalPackageAliasPlugin = require('./lib/webpack/plugin/resolve/LocalPackageAliasPlugin');
+const TerraDevSiteEntrypoints = require('./lib/webpack/plugin/TerraDevSiteEntrypoints');
```
Comment (mjhenkes) [inline index.js:3]: These are now included in the dev site webpack plugin by default. Should we still export them? They _could_ be used stand alone.... i lean toward removing them.

File: src/pages/_ComponentToolbar.jsx [hunk 5]
```diff
@@ -0,0 +1,63 @@
+import React from 'react';
```
Comment (mjhenkes) [inline src/pages/_ComponentToolbar.jsx:1]: This component may be removed depending on where we land for 'quick' actions to change the theme or locale.

File: src/pages/_ContentLoaded.jsx [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+  // useEffect(() => {
+  //   if (!window.location || window.location.length < 2) {
+  //     return;
+  //   }
+  //   const elementName = window.location.hash.slice(1);
+  //   const element = document.getElementById(elementName);
+  //   if (element) {
+  //     element.scrollIntoView();
+  //   }
+  // }, []);
```
Comment (mjhenkes) [inline src/pages/_ContentLoaded.jsx:34]: hash links appear to be working, but we previously had to use this to ensure the hash link was navigated to. I've left it for now until i'm satisfied we don't need it.

File: src/pages/_DevSitePage.jsx [hunk 7]
```diff
@@ -0,0 +1,150 @@
...
+
+  // if (hasLocales) {
+  //   pageActions.push({
+  //     key: 'locale',
+  //     label: 'Locale',
+  //     icon: <IconLocationPin />,
+  //     onSelect: () => { setShowLocale(true); },
+  //     buttonRefCallback: (ref) => { localeButtonRef.current = ref; },
+  //   });
+  // }
```
Comment (mjhenkes) [inline src/pages/_DevSitePage.jsx:95]: we may re-enable these depending on where we land on quick actions to change the theme and locale.

File: src/pages/_DevSitePage.jsx [hunk 8]
```diff
@@ -0,0 +1,150 @@
...
+      && (
+        <ContentSettingsMenu
+          text="Theme"
+          items={appSettings.themes}
+          selectedKey={appSettings.currentTheme}
+          onChange={onChangeTheme}
+          targetRef={themeButtonRef.current}
+          onRequestClose={() => setShowThemeMenu(false)}
+        />
+      )}
```
Comment (mjhenkes) [inline src/pages/_DevSitePage.jsx:143]: these might get removed in the future.

File: src/site/Site.jsx [hunk 9]
```diff
@@ -0,0 +1,56 @@
...
+      {({ currentLocale, currentThemeClassName }) => (
+        <BrowserRouter basename={siteConfig.basename}>
+          <Router sites={siteConfig.sites} routesMap={siteConfig.routesMap}>
+            <ApplicationBase
+              locale={currentLocale}
+              themeName={currentThemeClassName}
+            >
+              <TerraMdxProvider>
+                <DevSiteApplicationContainer titleConfig={siteConfig.titleConfig}>
+                  {SessionProvider ? (
```
Comment (mjhenkes) [inline src/site/Site.jsx:37]: Session provider prop is forward looking for when we update orion-dev-site

File: src/site/_DevSiteRouter.jsx [hunk 10]
```diff
@@ -0,0 +1,63 @@
...
+   * The map of routes to redirect to
+   */
+  routesMap: routesMapPropType.isRequired,
+  /**
+   * Children
+   */
+  children: PropTypes.node.isRequired,
+};
+
+const DevSiteRouter = ({
```
Comment (mjhenkes) [inline src/site/_DevSiteRouter.jsx:24]: This class does all the awkward routing for us, routing the root to the first content item, routing /primaryNavItem to the first content item of that type and flipping to other sites based on their reserved routes.

File: src/site/_DevSiteRouter.jsx [hunk 11]
```diff
@@ -0,0 +1,63 @@
...
+  sites,
+  routesMap,
+  children,
+}) => {
+  const isRoot = useRouteMatch('/');
+  const location = useLocation();
+
+  // Remove # Route if at root.
+  if (isRoot && location.hash.startsWith('#/')) {
```
Comment (mjhenkes) [inline src/site/_DevSiteRouter.jsx:33]: i considered removing this hash routing redirect, but it's not too expensive.

File: src/site/index.jsx [hunk 12]
```diff
@@ -0,0 +1 @@
+export { default } from './Site';
```
Comment (mjhenkes) [inline src/site/index.jsx:1]: this is exported to be re-used by orion-dev-site

File: src/terra-dev-site/extended/extended.extended.jsx [hunk 13]
```diff
@@ -0,0 +1,7 @@
+import React from 'react';
+
+export default () => (
```
Comment (mjhenkes) [inline src/terra-dev-site/extended/extended.extended.jsx:3]: test content

File: src/terra-dev-site/snt/secondary-scroll-test/GoToButton.jsx [hunk 14]
```diff
@@ -26,13 +26,13 @@ const GoToButton = (props) => {
   const {
     path,
     history,
-    ...customProps
+    // ...customProps
```
Comment (mjhenkes) [inline src/terra-dev-site/snt/secondary-scroll-test/GoToButton.jsx:29]:
```suggestion
```

File: src/terra-dev-site/test/loaders/PropsTableExample.jsx [hunk 15]
```diff
@@ -1,6 +1,5 @@
 import React from 'react';
 import PropTypes from 'prop-types';
-import { injectIntl, intlShape } from 'react-intl';
```
Comment (mjhenkes) [inline src/terra-dev-site/test/loaders/PropsTableExample.jsx:3]: removed to not depend on react-intl

File: src/terra-dev-site/test/markdownCheatSheet.test.mdx [hunk 16]
```diff
@@ -207,7 +207,7 @@ Inline `code` has `back-ticks around` it.
 
 Inline `code` has `back-ticks around` it.
 
-Blocks of code are either fenced by lines with three back-ticks <code>```</code>, or are indented with four spaces. I recommend only using the fenced code blocks -- they're easier and only they support syntax highlighting.
```
Comment (mjhenkes) [inline src/terra-dev-site/test/markdownCheatSheet.test.mdx:210]: this caused weird formatting

File: src/terra-dev-site/tool/terra-dev-site/configPropsTable.jsx [hunk 17]
```diff
@@ -0,0 +1,179 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+
+/* eslint-disable react/forbid-prop-types, react/no-unused-prop-types */
+const propTypes = {
```
Comment (mjhenkes) [inline src/terra-dev-site/tool/terra-dev-site/configPropsTable.jsx:5]: i threw this together to show terra-dev-site config as a props table instead of having to build out a table myself.

File: src/terra-dev-site/tool/terra-dev-site/configPropsTable.jsx [hunk 18]
```diff
@@ -0,0 +1,179 @@
...
+  //   ],
+  // }, {
+  //   path: '/components',
+  //   text: 'Components',
+  //   contentExtension: 'doc',
+  // }, {
+  //   path: '/tests',
+  //   text: 'Tests',
+  //   contentExtension: 'test',
+  // }],
```
Comment (mjhenkes) [inline src/terra-dev-site/tool/terra-dev-site/configPropsTable.jsx:156]: props table loader can't handle a complex default object. Needs looked into in a future PR.

File: src/test-extension/TestExtension.jsx [hunk 19]
```diff
@@ -1,25 +1,23 @@
 import React from 'react';
-import ContentContainer from 'terra-content-container';
-import ActionHeader from 'terra-action-header';
-import { DisclosureManagerContext } from 'terra-application/lib/disclosure-manager';
-import StatusView from 'terra-status-view';
+import PropTypes from 'prop-types';
```
Comment (mjhenkes) [inline src/test-extension/TestExtension.jsx:2]: testing only

File: src/webpack/loaderUtils/generateNavigationConfig.js [hunk 20]
```diff
@@ -0,0 +1,372 @@
...
+      routes: slicedDir,
+      contentPath,
+      ext,
+      contentImports,
+      url,
+      pageConfig,
+    });
+  } else {
+    // if this is a leaf page, add the content path and type to the config.
+    // configCopy.content = contentPath;
```
Comment (mjhenkes) [inline src/webpack/loaderUtils/generateNavigationConfig.js:58]:
```suggestion
```

File: src/webpack/plugin/TerraDevSiteEntrypoints.js [hunk 21]
```diff
@@ -0,0 +1,7 @@
+/**
+ * Default entries for terra-dev-site
+ */
+module.exports = {
```
Comment (mjhenkes) [inline src/webpack/plugin/TerraDevSiteEntrypoints.js:4]: i should be able to remove this with webpack v5

File: src/webpack/templates/index.html [hunk 22]
```diff
@@ -0,0 +1,19 @@
+<!doctype html>
```
Comment (mjhenkes) [inline src/webpack/templates/index.html:1]: this html template has be significantly simplified

File: README.md [hunk 23]
```diff
@@ -15,35 +15,13 @@
 [![Dependencies status](https://badgen.net/david/dep/cerner/terra-dev-site)](https://david-dm.org/cerner/terra-dev-site)
 [![devDependencies status](https://badgen.net/david/dev/cerner/terra-dev-site)](https://david-dm.org/cerner/terra-dev-site?type=dev)
 
-Dynamically builds a site based on site configuration, navigation configuration and page configuration.
+A webpack plugin to dynamically builds a terra-application documentation and testing site. See [terra-ui](https://engineering.cerner.com/terra-ui/dev_tools/terra-dev-site/terra-dev-site/about) for documentation.
```
Comment (emilyrohrbough) [inline README.md:18]:
```suggestion
A webpack plugin to dynamically build a documentation and testing site using terra-application as the applicaiton foundation. See [terra-ui](https://engineering.cerner.com/terra-ui/dev_tools/terra-dev-site/terra-dev-site/about) for documentation.
```

File: index.js (hunk 1 above)
Comment (emilyrohrbough) [reply index.js:1]: Should these be scoped under a config file still? That'd align with terra-functional-testing: https://github.com/cerner/terra-toolkit/tree/main/packages/terra-functional-testing/src/config

File: index.js (hunk 4 above)
Comment (emilyrohrbough) [reply index.js:3]: I vote remove them and expose them later on if requested or needed. Less (can) = more.

File: README.md [hunk 24]
```diff
@@ -15,35 +15,13 @@
...
-This component requires the following peer dependencies be installed in your app for the component to properly function.
-
-| Peer Dependency | Version |
-|-|-|
-| react | ^16.8.5 |
-| react-dom | ^16.8.5 |
-| terra-toolkit | ^5.2.0 |
-| webpack | ^4.28.1 |
+```bash
+npm install --save-dev @cerner/terra-dev-site
```
Comment (emilyrohrbough) [inline README.md:23]: Can we also list the peer dependencies to this quick copy & paste command?

File: src/modals/_ApplicataionSwitcherModal.jsx [hunk 25]
```diff
@@ -0,0 +1,43 @@
+import React from 'react';
+import PropTypes from 'prop-types';
+import List, { Item } from 'terra-list';
+import Hyperlink from 'terra-hyperlink';
+import ApplicationModal from '@cerner/terra-application/lib/application-modal/ApplicationModal';
```
Comment (emilyrohrbough) [inline src/modals/_ApplicataionSwitcherModal.jsx:5]: 100% curious, is it possible to use this import?

```suggestion
import ApplicationModal from '@cerner/terra-application/lib/application-modal';
```

File: src/modals/_ApplicataionSwitcherModal.jsx [hunk 26]
```diff
@@ -0,0 +1,43 @@
...
+   */
+  onRequestClose: PropTypes.func.isRequired,
+};
+
+const ApplicationSwitcherModal = ({ onRequestClose, sites }) => (
+  <ApplicationModal
+    title="Application Switcher"
+    onRequestClose={onRequestClose}
+  >
+    <List dividerStyle="bottom-only">
```
Comment (emilyrohrbough) [inline src/modals/_ApplicataionSwitcherModal.jsx:31]: Can we use the build-in list adding styles instead of adding custom padding on the Hyperlinks?

File: src/modals/_ApplicataionSwitcherModal.jsx [hunk 27]
```diff
@@ -0,0 +1,43 @@
...
+      {sites.map(site => (
+        <Item key={site.url}>
```
Comment (emilyrohrbough) [inline src/modals/_ApplicataionSwitcherModal.jsx:33]: Can we add the `isSelectable` prop to enable the hover styles for the list instead of adding custom hover styles on the hyperlink?

File: src/modals/_SearchModal.jsx [hunk 28]
```diff
@@ -112,26 +112,20 @@ const Search = ({ fetchSearchItems, onItemSelected }) => {
   }, []);
 
   return (
-    <ContentContainer
+    <ApplicationModal
       className={cx(theme.className)}
```
Comment (emilyrohrbough) [inline src/modals/_SearchModal.jsx:116]: Is the theme context handed by ApplicationModal? Do we need to grab it here and pass it down?

File: src/modals/_SearchModal.jsx [hunk 29]
```diff
@@ -1,28 +1,30 @@
...
-import classNames from 'classnames/bind';
-import { ThemeContext } from 'terra-application/lib/theme';
-import styles from './search.module.scss';
 
-const cx = classNames.bind(styles);
+import { pageConfigPropType } from '../site/siteConfigPropTypes';
+
+import styles from './SearchModal.module.scss';
+
+const cx = classNamesBind.bind(styles);
```
Comment (emilyrohrbough) [inline src/modals/_SearchModal.jsx:16]: I might be missing it, but is `search-field` the only css class being applied from https://github.com/cerner/terra-dev-site/blob/2adbedcfec6b91f2ccbb2135d5fe3d4fdf56b941/src/modals/SearchModal.module.scss#L5?

File: src/modals/_SearchModal.jsx [hunk 30]
```diff
@@ -146,18 +140,21 @@ const Search = ({ fetchSearchItems, onItemSelected }) => {
...
-    </ContentContainer>
+    </ApplicationModal>
   );
 };
 
-Search.propTypes = propTypes;
+SearchModal.propTypes = propTypes;
 
-export default Search;
+export default SearchModal;
```
Comment (emilyrohrbough) [inline src/modals/_SearchModal.jsx:160]: Should the search.module.scss theme files be renamed to SearchModal.module.scss?

File: src/pages/_LoadingOverlay.jsx [hunk 31]
```diff
@@ -15,7 +15,11 @@ const LoadingPage = () => {
     return () => { isActive = false; };
   }, []);
 
-  return <ApplicationLoadingOverlay isOpen={state.isOpen} />;
+  return (
+    <div data-terra-dev-site-loading data-terra-test-loading>
```
Comment (emilyrohrbough) [inline src/pages/_LoadingOverlay.jsx:19]: Can these data attributes be applied on the overlay directly?

File: src/site/siteConfigPropTypes.js [hunk 32]
```diff
@@ -21,105 +21,161 @@ const settingsConfigPropType = PropTypes.shape({
...
 /**
- * Menu items for side navigation
+ * Path to imports map
+ */
+const contentImportsPropType = PropTypes.object;
+/**
+ * Path to page config map
  */
-const menuItemsPropType = PropTypes.PropTypes.objectOf(menuItemPropType);
+const pageConfigPropType = PropTypes.object;
```
Comment (emilyrohrbough) [inline src/site/siteConfigPropTypes.js:108]: What is the pageConfig shape?

File: src/site/siteConfigPropTypes.js [hunk 33]
```diff
@@ -21,105 +21,161 @@ const settingsConfigPropType = PropTypes.shape({
...
+/**
+ * Short routes to content routes.
+ */
+const routesMapPropType = PropTypes.object;
```
Comment (emilyrohrbough) [inline src/site/siteConfigPropTypes.js:112]: What is the routesMap shape?

File: tests/wdio/marked-spec.js [hunk 34]
```diff
@@ -1,6 +1,7 @@
 Terra.describeViewports('md', ['huge'], () => {
   it('renders md', () => {
     browser.url('/raw/test/cerner-terra-dev-site/md');
+    browser.moveToObject('#root', 0, 900);
```
Comment (emilyrohrbough) [inline tests/wdio/marked-spec.js:4]:
```suggestion
    browser.moveToObject('#root', 0, 768);
```
So we can testing in firefox/IE without errors. (Can't remember which one errors out if the position is larger than the viewport height).

File: tests/wdio/mdx-spec.js [hunk 35]
```diff
@@ -1,13 +1,15 @@
 Terra.describeViewports('mdx', ['huge'], () => {
   it('renders mdx', () => {
     browser.url('/raw/test/cerner-terra-dev-site/mdx');
+    browser.moveToObject('#root', 0, 900);
```
Comment (emilyrohrbough) [inline tests/wdio/mdx-spec.js:4]:
```suggestion
    browser.moveToObject('#root', 0, 768);
```

File: tests/wdio/mdx-spec.js [hunk 36]
```diff
@@ -1,13 +1,15 @@
...
     Terra.validates.element('mdx');
   });
 
   it('follows the link', () => {
     browser.url('/raw/test/cerner-terra-dev-site/relative-link');
     Terra.validates.element('relative link');
     browser.click('[class*="MarkdownTags-module__a"]');
+    browser.moveToObject('#root', 0, 900);
```
Comment (emilyrohrbough) [inline tests/wdio/mdx-spec.js:12]:
```suggestion
    browser.moveToObject('#root', 0, 768);
```

File: tests/wdio/secondaryNavigation-spec.js [hunk 37]
```diff
@@ -4,55 +4,3 @@ Terra.describeViewports('secondary nav', ['tiny', 'huge'], () => {
     Terra.validates.element({ selector: '#root' });
   });
 });
-
-Terra.describeViewports('secondary scroll multiple files', ['huge'], () => {
```
Comment (emilyrohrbough) [inline tests/wdio/secondaryNavigation-spec.js:8]: Was this functionality removed?

Comment (mjhenkes) [reply tests/wdio/secondaryNavigation-spec.js:8]: This code now lives in terra-application in the secondary navigation layout. Not appropriate to test here anymore.

File: index.js (hunk 1 above)
Comment (mjhenkes) [reply index.js:1]: They aren't a shared config file like the wdio config. This houses the webpack plugins so i think they're scoped appropriately.

File: src/pages/_LoadingOverlay.jsx (hunk 31 above)
Comment (mjhenkes) [reply src/pages/_LoadingOverlay.jsx:19]: Maybe? I feel more comfortable adding them here like this though. It's a temporary div shown during loading.

File: src/site/siteConfigPropTypes.js (hunk 32 above)
Comment (mjhenkes) [reply src/site/siteConfigPropTypes.js:108]: It's a map of a random key to an object. I didn't look very hard but didn't see a clean way to represent it with prop types.

File: src/site/siteConfigPropTypes.js (hunk 33 above)
Comment (mjhenkes) [reply src/site/siteConfigPropTypes.js:112]: It's a map of a random key to an object. I didn't look very hard but didn't see a clean way to represent it with prop types.

File: src/modals/_SearchModal.jsx (hunk 30 above)
Comment (mjhenkes) [reply src/modals/_SearchModal.jsx:160]: Yes it should

File: src/modals/_SearchModal.jsx (hunk 28 above)
Comment (mjhenkes) [reply src/modals/_SearchModal.jsx:116]: The modal doesn't directly need the theme context it just happens to be the first div wrapping all search content. We could have the same effect by adding it to the toolbar and search items independently.

File: src/modals/_ApplicataionSwitcherModal.jsx (hunk 25 above)
Comment (mjhenkes) [reply src/modals/_ApplicataionSwitcherModal.jsx:5]: In the future, yes probably, but as of now we haven't added the index to the folder to import from.

File: src/modals/_ApplicataionSwitcherModal.jsx (hunk 26 above)
Comment (mjhenkes) [reply src/modals/_ApplicataionSwitcherModal.jsx:31]: Yes

File: src/modals/_ApplicataionSwitcherModal.jsx (hunk 27 above)
Comment (mjhenkes) [reply src/modals/_ApplicataionSwitcherModal.jsx:33]: I'll remove the highlight altogether and rely on the hyperlinks hover style.

File: README.md (hunk 24 above)
Comment (mjhenkes) [reply README.md:23]: updated

File: CHANGELOG.md [hunk 38]
```diff
@@ -15,6 +15,15 @@
   * `locales` has been removed from site config. As of 6.23 Locales are pulled from the global `TERRA_AGGREGATED_LOCALES` variable provided by terra-toolkit v5.21.0.
   * Changed to a scoped package. `terra-dev-site` -> `@cerner/terra-dev-site`
   * Remove defaulting to devtool: source-map when in production with no devtool enabled. This was causing slow builds for large projects.
+  * Terra-dev-site fully converted to a webpack plugin.
```
Comment (ryanthemanuel) [inline CHANGELOG.md:18]: Are these all truly breaking?  It might be helpful for consumers to know what the specific breaking changes are.

File: README.md [hunk 39]
```diff
@@ -15,35 +15,16 @@
...
-This component requires the following peer dependencies be installed in your app for the component to properly function.
-
-| Peer Dependency | Version |
-|-|-|
-| react | ^16.8.5 |
-| react-dom | ^16.8.5 |
-| terra-toolkit | ^5.2.0 |
-| webpack | ^4.28.1 |
+// Install Peer Dependencies
+npm install --save-dev @cerner/terra-application react-dom react webpack
```
Comment (ryanthemanuel) [inline README.md:26]: This will install webpack 5 and react 17.

Not sure if we can do:

npm install --save-dev @cerner/terra-application react-dom@^16.8.5 react@^16.8.5 webpack@^4.28.1

File: src/layouts/_DevSiteNavigationLayout.jsx [hunk 40]
```diff
@@ -0,0 +1,126 @@
...
+  /**
+   * The site config for the application.
+   */
+  siteConfig: siteConfigPropType.isRequired,
+};
+
+const DevSiteNavigationLayout = ({ siteConfig }) => {
+  const location = useLocation();
+  const history = useHistory();
+  const [showSettingsModal, setShowSettingsModal] = React.useState(false);
```
Comment (ryanthemanuel) [inline src/layouts/_DevSiteNavigationLayout.jsx:27]: Initialize all 3 of these to false for consistency?

File: README.md (hunk 39 above)
Comment (mjhenkes) [reply README.md]: lol

File: src/layouts/_DevSiteNavigationLayout.jsx (hunk 40 above)
Comment (mjhenkes) [reply src/layouts/_DevSiteNavigationLayout.jsx:27]: well, i'm actually cheating with the second two, they aren't set to true or false, but have an object with a render function placed in them, so we render based on the presence of an object.

File: CHANGELOG.md (hunk 38 above)
Comment (mjhenkes) [reply CHANGELOG.md:18]: It's debatable, but i'll break some of these out.

File: src/modals/SettingsModal.module.scss [hunk 41]
```diff
@@ -0,0 +1,9 @@
+:local {
+  .container {
+    padding: 0.7143rem;
```
Comment (ryanthemanuel) [inline src/modals/SettingsModal.module.scss:3]: Why the different rounding on line 3 and 7?

File: src/pages/_ContentLoaded.jsx (hunk 6 above)
Comment (ryanthemanuel) [reply src/pages/_ContentLoaded.jsx:34]: > left it for now until i'm satisfied we don't need it.

left it = left it commented?  I just want to make sure we don't forget to delete it at some point.

File: src/pages/_ContentSettingsMenu.jsx [hunk 42]
```diff
@@ -0,0 +1,70 @@
...
+import Menu from 'terra-menu';
+
+const propTypes = {
+  /**
+   * Button text
+   */
+  text: PropTypes.string.isRequired,
+
+  /**
+   * menu items
```
Comment (ryanthemanuel) [inline src/pages/_ContentSettingsMenu.jsx:12]:
```suggestion
   * Menu items
```

File: src/pages/_ContentSettingsMenu.jsx [hunk 43]
```diff
@@ -0,0 +1,70 @@
...
+   */
+  items: PropTypes.arrayOf(PropTypes.string).isRequired,
+
+  /**
+   * Selected menu item
```
Comment (ryanthemanuel) [inline src/pages/_ContentSettingsMenu.jsx:17]:
```suggestion
   * Key for the selected menu item
```

File: src/pages/_DevSitePageErrorBoundary.jsx [hunk 44]
```diff
@@ -1,17 +1,14 @@
 import React from 'react';
 import PropTypes from 'prop-types';
-import ErrorPage from './_ErrorPage';
+import ApplicationStatusOverlay from '@cerner/terra-application/lib/application-status-overlay';
+
+import ContentLoadedContainer from './_ContentLoaded';
 
 const propTypes = {
   /**
    * children are children
```
Comment (ryanthemanuel) [inline src/pages/_DevSitePageErrorBoundary.jsx:9]: Profound :) Can we update this description?

File: src/site/Site.jsx [hunk 45]
```diff
@@ -0,0 +1,56 @@
...
+import Router from './_DevSiteRouter';
+import DevSiteApplicationContainer from './_DevSiteApplicationContainer';
+
+const propTypes = {
+  /**
+   * The site config for the application.
+   */
+  siteConfig: siteConfigPropType.isRequired,
+  /**
+   * The A session provider
```
Comment (ryanthemanuel) [inline src/site/Site.jsx:20]:
```suggestion
   * The session provider
```

File: src/pages/_DevSitePageErrorBoundary.jsx (hunk 44 above)
Comment (mjhenkes) [reply src/pages/_DevSitePageErrorBoundary.jsx:9]: Recommendations? I never know what to say about 'children'.

File: src/modals/SettingsModal.module.scss (hunk 41 above)
Comment (mjhenkes) [reply src/modals/SettingsModal.module.scss:3]: 🤷‍♂️

File: src/pages/_ContentLoaded.jsx (hunk 6 above)
Comment (mjhenkes) [reply src/pages/_ContentLoaded.jsx:34]: yeah, left it commented until i'm sure we don't need it.

File: src/modals/_SearchModal.jsx (hunk 28 above)
Comment (tbiethman) [reply src/modals/_SearchModal.jsx:116]: ApplicationModal does not take custom props, so I don't think this is doing anything right now.

Comment (mjhenkes) [reply src/modals/_SearchModal.jsx:116]: lol

File: src/site/_DevSiteApplicationContainer.jsx [hunk 46]
```diff
@@ -0,0 +1,30 @@
...
+  /**
+   * The title config for the app, used for the container's application name.
+   */
+  titleConfig: titleConfigShape.isRequired,
+};
+
+const DevSiteApplicationContainer = ({ titleConfig, children }) => {
+  const isRaw = useRouteMatch('/raw');
+  return (
+    <ApplicationContainer applicationName={titleConfig.titleConfig} skipToLinksAreDisabled={!!isRaw} unloadPromptIsDisabled={!!isRaw}>
```
Comment (tbiethman) [inline src/site/_DevSiteApplicationContainer.jsx:22]: ??

```suggestion
    <ApplicationContainer applicationName={titleConfig.title} skipToLinksAreDisabled={!!isRaw} unloadPromptIsDisabled={!!isRaw}>
```

Comment (mjhenkes) [reply src/site/_DevSiteApplicationContainer.jsx:22]: that makes sense, you probably don't want `undefined` to be your application name.

Comment (mjhenkes) [reply src/site/_DevSiteApplicationContainer.jsx]: updated

File: src/webpack/loaderUtils/configHelpers.js [hunk 47]
```diff
@@ -34,38 +29,42 @@ const getNamespace = (directory, namespace) => {
...
-/** Returns an object of the end most extention and the filename minus that extension.
- * This may be used mulitiple times on a string to retirve all extensions.
+/** Returns an object of the end most extension and the filename minus that extension.
+ * This may be used multiple times on a string to retrieve all extensions.
  */
-const parseExtension = fileName => ({
-  name: fileName.replace(/\.[^.]+$/, ''),
-  extension: /[^.]+$/.exec(fileName)[0],
-});
+const parseExtension = fileName => {
```
Comment (emilyrohrbough) [inline src/webpack/loaderUtils/configHelpers.js:52]: Can we add jsdoc on the param?

File: src/webpack/loaderUtils/configHelpers.js [hunk 48]
```diff
@@ -34,38 +29,42 @@ const getNamespace = (directory, namespace) => {
...
+  const result = /\.([^.]+$)/.exec(fileName);
+
+  let extension;
+  if (result) {
+    [, extension] = result;
```
Comment (emilyrohrbough) [inline src/webpack/loaderUtils/configHelpers.js:57]: before this was pulling the first value? not the second? is that right?

File: src/webpack/loaderUtils/configHelpers.js [hunk 49]
```diff
@@ -14,12 +14,7 @@ const startCase = (string) => {
 /**
```
Comment (emilyrohrbough) [inline src/webpack/loaderUtils/configHelpers.js:14]: Are there any tests around these ?

File: src/webpack/loaders/devSiteEntry.js [hunk 50]
```diff
@@ -0,0 +1,83 @@
+const lodashTemplate = require('lodash.template');
+const { getOptions } = require('loader-utils');
+
+const generateNavigationConfig = require('../loaderUtils/generateNavigationConfig');
+
+/**
+ * Generate the example with the supplied file.
+ * Don't use an arrow function
```
Comment (emilyrohrbough) [inline src/webpack/loaders/devSiteEntry.js:8]: Why not arrorw func? 

can we doc what template is?

File: src/webpack/loaders/devSiteEntry.js [hunk 51]
```diff
@@ -0,0 +1,83 @@
...
+  const addImport = (path) => {
+    let ident = imports[path];
+    if (ident) {
+      return ident;
+    }
+    ident = `import${index}`;
+    index += 1;
+    imports[path] = ident;
+    return ident;
+  };
```
Comment (emilyrohrbough) [inline src/webpack/loaders/devSiteEntry.js:25]: Could this be static outside of the loader func?

File: src/webpack/loaders/devSiteEntry.js [hunk 52]
```diff
@@ -0,0 +1,83 @@
...
+
+  const imports = {};
+  let index = 0;
+
+  const addImport = (path) => {
+    let ident = imports[path];
+    if (ident) {
+      return ident;
+    }
+    ident = `import${index}`;
```
Comment (emilyrohrbough) [inline src/webpack/loaders/devSiteEntry.js:21]: Should this be:
```suggestion
    ident = `import(${index})`;
```

File: src/webpack/loaders/devSiteEntry.js (hunk 51 above)
Comment (mjhenkes) [reply src/webpack/loaders/devSiteEntry.js:25]: Originally it was, but then imports from other plugins started showing up in all plugins. So i had to make it instance based.

File: src/webpack/loaders/devSiteEntry.js (hunk 52 above)
Comment (emilyrohrbough) [reply src/webpack/loaders/devSiteEntry.js:21]: What does index represent here? I'm not following exactly what it's representing

File: src/webpack/loaderUtils/configHelpers.js (hunk 49 above)
Comment (mjhenkes) [reply src/webpack/loaderUtils/configHelpers.js:14]: They're indirectly tested through the generate navigation config tests

File: src/webpack/loaders/devSiteEntry.js [hunk 53]
```diff
@@ -0,0 +1,83 @@
...
+  const {
+    contentImports,
+    navigationConfig,
+    routesMap,
+    pageConfig,
+  } = generateNavigationConfig({
+    siteConfig,
+    resolveExtensions,
+    mode: this.mode,
+    verbose: false,
```
Comment (emilyrohrbough) [inline src/webpack/loaders/devSiteEntry.js:53]: Will this always be false? Should verbose be removed?

File: src/webpack/loaderUtils/configHelpers.js (hunk 48 above)
Comment (mjhenkes) [reply src/webpack/loaderUtils/configHelpers.js:57]: it was a bug previously, we want the first capture group here not the full regex match.

File: src/webpack/loaders/devSiteEntry.js [hunk 54]
```diff
@@ -0,0 +1,83 @@
...
+    contentDirectory,
+    isLernaMonoRepo,
+    addContextDependency: this.addContextDependency,
+    // getLogger is undefined in the loader runner for tests, but never in acutal usage.
```
Comment (emilyrohrbough) [inline src/webpack/loaders/devSiteEntry.js:57]: Should this be mocked for tests?

File: src/webpack/loaders/devSiteEntry.js (hunk 50 above)
Comment (mjhenkes) [reply src/webpack/loaders/devSiteEntry.js:8]: my comment got truncated on my frequent copying of the loader.

> Don't use an arrow function or you wont have access to `this`

File: src/webpack/loaders/devSiteEntry.js (hunk 53 above)
Comment (mjhenkes) [reply src/webpack/loaders/devSiteEntry.js:53]: yep thats dead code

File: src/webpack/loaders/devSiteEntry.js (hunk 54 above)
Comment (mjhenkes) [reply src/webpack/loaders/devSiteEntry.js:57]: not easily no

File: src/webpack/loaders/devSiteEntry.js [hunk 55]
```diff
@@ -0,0 +1,83 @@
...
+    entryPath,
+    title: siteConfig.titleConfig.title,
+    headline: siteConfig.titleConfig.headline,
+    subline: siteConfig.titleConfig.subline,
+    defaultTheme: siteConfig.defaultTheme,
+    defaultLocale: siteConfig.defaultLocale,
+    defaultDirection: siteConfig.defaultDirection,
+    basename,
+    contentImports,
+    navigationConfig: JSON.stringify(navigationConfig),
```
Comment (emilyrohrbough) [inline src/webpack/loaders/devSiteEntry.js:71]: Why do these need to be JSON. stringify? Won't the lodash template be able to read it in?

File: src/webpack/plugin/SitePlugin.js [hunk 56]
```diff
@@ -0,0 +1,287 @@
...
+ */
+class SitePlugin {
+  constructor({
+    entry,
+    config,
+    applyDefaults,
+    contentDirectory,
+  } = {}) {
+    // Apply defaults to the config.
+    this.siteConfig = applyDefaults(config);
```
Comment (emilyrohrbough) [inline src/webpack/plugin/SitePlugin.js:29]: What happens if applyDefaults is undefined?

Comment (mjhenkes) [reply src/webpack/plugin/SitePlugin.js:29]: It should blow up, applyDefaults is required.

File: src/webpack/loaders/devSiteEntry.js (hunk 55 above)
Comment (mjhenkes) [reply src/webpack/loaders/devSiteEntry.js:71]: I could stringify it here or in the lodash template, but it needs to be in string form so I can write out the file.

File: src/webpack/loaders/devSiteEntry.js (hunk 52 above)
Comment (mjhenkes) [reply src/webpack/loaders/devSiteEntry.js:21]: nah, this is the very generically named import name, so it would render like this

```javascript
 import import0 from 'terra-icon/lib/icon/IconAllergy';
```

Comment (mjhenkes) [reply src/webpack/loaders/devSiteEntry.js:21]: I'll rename it importName to reduce confusion.

File: src/webpack/loaderUtils/configHelpers.js (hunk 47 above)
Comment (mjhenkes) [reply src/webpack/loaderUtils/configHelpers.js:52]: fileName, the name of the file 😝

File: src/webpack/plugin/SitePlugin.js [hunk 57]
```diff
@@ -0,0 +1,287 @@
...
+        babelLoader,
+        {
+          loader: 'devSiteEntry',
+          options: {
+            entryPath: this.entry,
+            siteConfig: this.siteConfig,
+            sites: otherSites,
+            basename,
+            resolveExtensions: compiler.options.resolve.extensions,
+            isLernaMonoRepo,
```
Comment (emilyrohrbough) [inline src/webpack/plugin/SitePlugin.js:266]: I think you could remove the monorepo if-else path/pattern logic in generateNavigationConfig addWatchContentDirectories and getSearchPatterns if you pass down the rootDirectories or the resolves root path.

The `isLernaMonoRepo` is just passed down till it's used in generateNavigationConfig from what I can tell

Comment (mjhenkes) [reply src/webpack/plugin/SitePlugin.js:266]: It's true, but I'm not sure it makes much of a difference performance wise. either way I still need to glob the directories and would still have to build out the entrypoint regex seprately.

Comment (mjhenkes) [reply src/webpack/plugin/SitePlugin.js:266]: i also don't want to glob if it's not a mono repo directory

File: src/webpack/plugin/SitePlugin.js [hunk 58]
```diff
@@ -0,0 +1,287 @@
...
+        },
+      ],
+    });
+
+    // Generate the index.html file for the site.
+    new HtmlWebpackPlugin({
+      title: this.siteConfig.titleConfig.title,
+      filename: this.htmlFileName,
+      template: path.join(__dirname, '..', 'templates', 'index.html'),
+      rootElementId: 'root',
```
Comment (emilyrohrbough) [inline src/webpack/plugin/SitePlugin.js:278]: Should this hard-code to root?

File: src/webpack/plugin/applyDefaults.js [hunk 59]
```diff
@@ -0,0 +1,62 @@
...
+    ],
+  }, {
+    path: '/components',
+    label: 'Components',
+    contentExtension: 'doc',
+  }, {
+    path: '/tests',
+    label: 'Tests',
+    contentExtension: 'test',
+  }],
```
Comment (emilyrohrbough) [inline src/webpack/plugin/applyDefaults.js:26]: Was there talk of breaking tests out into their own site? Assume this is here to maitian what exists today?

File: src/webpack/plugin/applyDefaults.js [hunk 60]
```diff
@@ -0,0 +1,62 @@
...
+  defaultDirection,
+  faviconFilePath = path.join(__dirname, '..', 'terra-favicon', '32px', 'favicon.ico'),
+  extensionItems = [],
+  headHtml = [],
+  pathPrefix,
+  sourceFolder = 'src',
+  distributionFolder = 'lib',
+  enableDebugLogging = false,
+  additionalConfig = {},
+} = {}) => ({
```
Comment (emilyrohrbough) [inline src/webpack/plugin/applyDefaults.js:43]: Probably not much different, but thoughts on using lodash.get's API for determine the fallback/default value?

File: src/webpack/plugin/applyDefaults.js (hunk 59 above)
Comment (mjhenkes) [reply src/webpack/plugin/applyDefaults.js:26]: yep, people could create a specific webpack config with reduced terra-dev-site config to only generate what is being tested. I think this config is up to the person and not terra-dev-site.

File: src/webpack/plugin/SitePlugin.js (hunk 58 above)
Comment (mjhenkes) [reply src/webpack/plugin/SitePlugin.js:278]: hard coding to root is correct, i could move this into the template but 🤷‍♂️

File: src/webpack/plugin/applyDefaults.js (hunk 60 above)
Comment (mjhenkes) [reply src/webpack/plugin/applyDefaults.js:43]: this method is nice in that it allows m to default specific entries if not defined and it doesn't introduce another dependency.

File: src/webpack/plugin/index.js [hunk 61]
```diff
@@ -0,0 +1,7 @@
+const SitePlugin = require('./SitePlugin');
+const applyDefaults = require('./applyDefaults');
+
+module.exports = {
+  SitePlugin,
+  applyDefaults,
```
Comment (emilyrohrbough) [inline src/webpack/plugin/index.js:6]: Why export applyDefaults?

Comment (mjhenkes) [reply src/webpack/plugin/index.js:6]: I reuse it in orion-dev-site.

Comment (mjhenkes) [reply src/webpack/plugin/index.js:6]:
```javascript
const { applyDefaults } = require('@cerner/terra-dev-site/lib/webpack/plugin');

const orionDevSiteApplyDefaults = ({
  user = {
    firstName: 'Demo',
    lastName: 'User',
    username: 'demouser',
  },
  ...config
}) => {
  const defaultedConfig = applyDefaults(config);
  defaultedConfig.additionalConfig.user = user;
  return defaultedConfig;
};

module.exports = orionDevSiteApplyDefaults;
```

File: src/webpack/plugin/SitePlugin.js [hunk 62]
```diff
@@ -0,0 +1,287 @@
...
+    const mdxLoader = getMdxLoader(compiler.options.output.publicPath);
+    compiler.options.module.rules = [{
+      // Drop loaders in a 'one of' block to avoid the original loaders applying on top of the new loaders.
+      // Only the first loader will apply and no others.
+      oneOf: [{
+        test: /\.mdx$/,
+        use: [
+          babelLoader,
+          mdxLoader,
+        ],
```
Comment (emilyrohrbough) [inline src/webpack/plugin/SitePlugin.js:85]: nit: based on naming, I'd have assumed this should be using the mdxLoader returned from getMdxLoader

File: src/webpack/plugin/SitePlugin.js [hunk 63]
```diff
@@ -0,0 +1,287 @@
...
+    oneTimeSetupComplete = true;
+
+    compiler.options.entry = {
+      ...compiler.options.entry,
+      rewriteHistory: '@cerner/terra-dev-site/lib/browser-router-redirect/rewriteHistory',
+      redirect: '@cerner/terra-dev-site/lib/browser-router-redirect/redirect',
+    };
+
+    // MODULE
+    const mdxLoader = getMdxLoader(compiler.options.output.publicPath);
```
Comment (emilyrohrbough) [inline src/webpack/plugin/SitePlugin.js:76]: Why break out getMdxLoader and babelLoader, but none of the other configs used here?

File: src/webpack/plugin/SitePlugin.js (hunk 62 above)
Comment (mjhenkes) [reply src/webpack/plugin/SitePlugin.js:85]: I'm confused, It does doesn't it?

File: src/webpack/plugin/SitePlugin.js [hunk 64]
```diff
@@ -0,0 +1,287 @@
...
+      ],
+    }];
+
+    // RESOLVE
+    // If plugins is not defined, define it.
+    if (!compiler.options.resolve.plugins) {
+      compiler.options.resolve.plugins = [];
+    }
+
+    // If a mono repo, update the rootDirectories to include all the packages.
```
Comment (emilyrohrbough) [inline src/webpack/plugin/SitePlugin.js:157]: This it so allow for a package to alias itself right?

File: src/webpack/plugin/SitePlugin.js (hunk 63 above)
Comment (mjhenkes) [reply src/webpack/plugin/SitePlugin.js:76]: because the babel and mdx loaders are reused throughout the other loaders.

File: src/webpack/plugin/SitePlugin.js (hunk 64 above)
Comment (mjhenkes) [reply src/webpack/plugin/SitePlugin.js:157]: yep

File: src/webpack/plugin/SitePlugin.js [hunk 65]
```diff
@@ -0,0 +1,287 @@
...
+    }).apply(compiler);
+  }
+
+  apply(compiler) {
+    // Use default public path else the env else /
+    let defaultPublicPath;
+    if (compiler.options.output && compiler.options.output.publicPath) {
+      defaultPublicPath = compiler.options.output.publicPath;
+    }
+    const publicPath = defaultPublicPath || process.env.TERRA_DEV_SITE_PUBLIC_PATH || '/';
```
Comment (emilyrohrbough) [inline src/webpack/plugin/SitePlugin.js:212]: Why is the webpack config's publicPath honored before `TERRA_DEV_SITE_PUBLIC_PATH`?

File: src/webpack/templates/index.html [hunk 66]
```diff
@@ -0,0 +1,19 @@
...
+<html>
+  <head>
+    <meta charset="utf-8">
+    <meta http-equiv="x-ua-compatible" content="ie=edge">
+    <meta name="viewport" content="width=device-width, initial-scale=1">
+    <%= htmlWebpackPlugin.options.headHtml.join('\n    ') %>
+    <% if (htmlWebpackPlugin.options.rewriteHistory) { %>
+    <script src="/<%= compilation.entrypoints.get('rewriteHistory').getFiles()[0] %>"></script>
+    <% } %>
```
Comment (emilyrohrbough) [inline src/webpack/templates/index.html:10]: Indenting would make this easier to read. does it impact the output?
```suggestion
    <% if (htmlWebpackPlugin.options.rewriteHistory) { %>
      <script src="/<%= compilation.entrypoints.get('rewriteHistory').getFiles()[0] %>"></script>
    <% } %>
```

Comment (mjhenkes) [reply src/webpack/templates/index.html:10]: yes it does impact the output

File: src/webpack/loaderUtils/configHelpers.js (hunk 48 above)
Comment (emilyrohrbough) [reply src/webpack/loaderUtils/configHelpers.js:59]: Hey now, @StephenEsser has been big on doc everything lately and it does make it easier once you've been away from it for a while.

File: src/webpack/plugin/SitePlugin.js (hunk 65 above)
Comment (mjhenkes) [reply src/webpack/plugin/SitePlugin.js:212]: Good question, the env should probably override everything

File: src/webpack/templates/index.html (hunk 66 above)
Comment (mjhenkes) [reply src/webpack/templates/index.html:10]: funnily enough though, i don't need to flex that so i can remove the if

File: src/webpack/plugin/SitePlugin.js (hunk 58 above)
Comment (mjhenkes) [reply src/webpack/plugin/SitePlugin.js]: i updated the template

File: src/layouts/_DevSiteNavigationLayout.jsx (hunk 40 above)
Comment (ryanthemanuel) [reply src/layouts/_DevSiteNavigationLayout.jsx:27]: Could we rename them to settingsModalConfig or something instead?

File: src/layouts/_DevSiteSecondaryNavigationLayout.jsx [hunk 67]
```diff
@@ -0,0 +1,84 @@
...
+  NavigationItemContext,
+} from '@cerner/terra-application/lib/layouts';
+import { useLocation, useHistory } from 'react-router-dom';
+
+import DevSitePage from '../pages/_DevSitePage';
+import NotFoundPage from '../pages/_NotFoundPage';
+import { contentImportsShape, navigationConfigShape } from '../site/siteConfigShapes';
+
+const propTypes = {
+
```
Comment (ryanthemanuel) [inline src/layouts/_DevSiteSecondaryNavigationLayout.jsx:17]: Extra space here

File: src/pages/_ContentSettingsMenu.jsx [hunk 68]
```diff
@@ -0,0 +1,70 @@
...
+    isOpen
+    targetRef={() => targetRef}
+    onRequestClose={onRequestClose}
+  >
+    <Menu.ItemGroup
+      key={text}
+      onChange={(event, index) => {
+        onChange(items[index]);
+      }}
+
```
Comment (ryanthemanuel) [inline src/pages/_ContentSettingsMenu.jsx:55]: Extra line here.

File: src/site/_DevSiteApplicationContainer.jsx [hunk 69]
```diff
@@ -0,0 +1,30 @@
+import React from 'react';
+import { useRouteMatch } from 'react-router-dom';
+import PropTypes from 'prop-types';
+import ApplicationContainer from '@cerner/terra-application/lib/application-container/ApplicationContainer';
+
+import { titleConfigShape } from './siteConfigShapes';
+
+const propTypes = {
+  /**
+   * The A session provider
```
Comment (ryanthemanuel) [inline src/site/_DevSiteApplicationContainer.jsx:10]:
```suggestion
   * The session provider
```

File: src/site/siteConfigShapes.js [hunk 70]
```diff
@@ -0,0 +1,185 @@
...
+/**
+ * Path to page config map
+ */
+const pageConfigShape = PropTypes.object;
+/**
+ * Short routes to content routes.
+ */
+const routesMapShape = PropTypes.object;
+
+const titleConfigShape = PropTypes.shape({
```
Comment (ryanthemanuel) [inline src/site/siteConfigShapes.js:114]:
```suggestion
/**
 * Describes the title config
 */
const titleConfigShape = PropTypes.shape({
```

File: src/layouts/_DevSiteNavigationLayout.jsx (hunk 40 above)
Comment (mjhenkes) [reply src/layouts/_DevSiteNavigationLayout.jsx:27]: Renamed to `extensionModal` and `utilityModal`

File: src/site/_DevSiteApplicationContainer.jsx (hunk 69 above)
Comment (mjhenkes) [reply src/site/_DevSiteApplicationContainer.jsx]: this description was way off

File: src/site/siteConfigShapes.js (hunk 70 above)
Comment (mjhenkes) [reply src/site/siteConfigShapes.js:117]: updated in 885aab0

File: src/terra-dev-site/tool/terra-dev-site/setupGuide.e.tool.mdx [hunk 71]
```diff
@@ -0,0 +1,63 @@
...
+  "scripts": {
+    "start": "webpack-dev-server"
+  }
+}
+```
+
+After adding the start command to your package.json, run it and navigate to http://localhost:8080/ to view the site in your browser:
+
+```bash
+npm run start
```
Comment (ryanthemanuel) [inline src/terra-dev-site/tool/terra-dev-site/setupGuide.e.tool.mdx:50]: You can actually just do npm start right?

```suggestion
npm start
```

**Review by ryanthemanuel — APPROVED** [review]

File: src/layouts/_DevSiteSecondaryNavigationLayout.jsx [hunk 72]
```diff
@@ -0,0 +1,83 @@
...
+          )}
+        />
+      );
+    })
+  );
+
+  return (
+    <SecondaryNavigationLayout
+      id={id}
+      activeNavigationKey={location.pathname}
```
Comment (tbiethman) [inline src/layouts/_DevSiteSecondaryNavigationLayout.jsx:68]: I added a `label` prop to the SecondaryNavigationLayout that populates the header text within the side-nav panel. Previously it was defaulting to "Side Nav", which is lame. This label would likely want to match the primary navigation item label that it's associated to.

**Review by tbiethman — APPROVED** [review]

File: src/layouts/_DevSiteSecondaryNavigationLayout.jsx (hunk 72 above)
Comment (mjhenkes) [reply src/layouts/_DevSiteSecondaryNavigationLayout.jsx:68]: I'll apply this in a future update since there are upcoming changes to terra-app v2 styles that will have to be accounted for beyond the current shaw this PR is locked into.
